#############################################################################
# Generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#  Jan 28, 2019 12:39:44 PM EST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Segoe UI} -size 18 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font16
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 960x1080+694+-812
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2025 2335
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm iconify $top
    wm title $top "RasPianoScope"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra47 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 345 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 475 
    vTcl:DefineAlias "$top.fra47" "AppFrame" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra47
    canvas $site_3_0.can48 \
        -background {#000000} -borderwidth 2 -closeenough 1.0 -height 75 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground {#c4c4c4} \
        -selectforeground black -width 125 
    vTcl:DefineAlias "$site_3_0.can48" "FFT+TransferFunction" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.can48
    canvas $site_4_0.can58 \
        -background {#efc90c} -borderwidth 2 -closeenough 1.0 -height 83 \
        -insertbackground black -relief ridge -selectbackground {#c4c4c4} \
        -selectforeground black -width 483 
    vTcl:DefineAlias "$site_4_0.can58" "ControlCanvas1" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.can58
    label $site_5_0.lab61 \
        -background {#efc90c} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font16,object) -foreground {#000000} \
        -text {*Place control vector image here*} 
    vTcl:DefineAlias "$site_5_0.lab61" "Label1" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.lab61 \
        -in $site_5_0 -x 0 -y 20 -width 481 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.can58 \
        -in $site_4_0 -x 230 -y 450 -width 483 -relwidth 0 -height 83 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $site_3_0.can48
    canvas $site_3_0.can49 \
        -background {#000000} -borderwidth 2 -closeenough 1.0 -height 75 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground {#c4c4c4} \
        -selectforeground black -width 125 
    vTcl:DefineAlias "$site_3_0.can49" "Oscilloscope" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.can49
    canvas $site_4_0.can57 \
        -background {#efc90c} -borderwidth 2 -closeenough 1.0 -height 83 \
        -insertbackground black -relief ridge -selectbackground {#c4c4c4} \
        -selectforeground black -width 483 
    vTcl:DefineAlias "$site_4_0.can57" "ControlCanvas2" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.can57
    label $site_5_0.lab62 \
        -background {#efc90c} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font16,object) -foreground {#000000} \
        -text {*Place control vector image here*} 
    vTcl:DefineAlias "$site_5_0.lab62" "Label2" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.lab62 \
        -in $site_5_0 -x 0 -y 20 -anchor nw -bordermode ignore 
    place $site_4_0.can57 \
        -in $site_4_0 -x 240 -y 450 -width 483 -relwidth 0 -height 83 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $site_3_0.can49
    place $site_3_0.can48 \
        -in $site_3_0 -x 0 -y 0 -width 960 -relwidth 0 -height 540 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.can49 \
        -in $site_3_0 -x 0 -y 540 -width 960 -relwidth 0 -height 540 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.fra47
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra47 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1 -height 1080 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

